Addition of Navbar Component
dokc/rebuilding-explorers-world pull request #16
Opened 2022-10-10 17:38 UTC by coldn00dles

# New Pull Request

## SOLVES ISSUE #

- **:pencil: What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- Adds a navbar to the website
- **:pencil: What is the current behavior?** (You can also link to an open issue here)
- https://github.com/dokc/rebuilding-explorers-world/issues/5
- **:pencil: What is the new behavior (if this is a feature change)?**
- Visibility changes due to navbar being added
- **:pencil: Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
### :white_check_mark: Check List (Check all the applicable boxes)

- :white_check_mark: I have read [contributing.md](../contributing.md)
- :white_check_mark:I have followed the [code of conduct](../code_of_conduct.md)
- :white_check_mark: My code follows the style guidelines of this project.
- :white_check_mark: I have performed a self-review of my code.
- :white_check_mark: I have commented my code, particularly in hard-to-understand areas.
- :white_check_mark: My changes generate no new warnings.
- :white_check_mark: I have done `git pull` before adding my new changes.
- :white_check_mark: The title of my pull request is a short description of the requested changes.

### :pencil: Other Issues :

### :scroll: Screenshots (If Applicable)

Original :
Updated :

2022-10-11 04:45 UTC, AbhijithGanesh requested changes
Please make a component for your Navbar and please return them as a component

2022-10-11 04:46 UTC, AbhijithGanesh requested changes
We are using Astro and not Gatsby, please change accordingly.

2022-10-11 06:45 UTC, coldn00dles reviewed
Surely

2022-10-11 10:05 UTC, AbhijithGanesh requested changes

2022-10-11 10:05 UTC, AbhijithGanesh commented on src/components/navbar.astro
> +      }
Can you implement css separately? Or you can use [TailwindCss](https://tailwindcss.com/) to use class based styling.

2022-10-11 10:05 UTC, AbhijithGanesh commented on package.json
> -  "devDependencies": {}
We donot know why this was deleted, so revert please

2022-10-11 10:10 UTC, coldn00dles commented on package.json
> -  "devDependencies": {}
surely

2022-10-12 14:11 UTC, AbhijithGanesh approved these changes
LGTM

2022-10-12 14:11 UTC, merged